version: '3.8'
networks:
  waiting_for_conteiner:

services:

  bot:
    build: ./bot
    command: >
      sh -c "alembic upgrade head &&
      python3 -u __main__.py"
    volumes:
      - ./bot/:/usr/src/bot
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - "db:database"
      - redis

  db:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U weather" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]


