"""Add relationship

Revision ID: 002
Revises: 001
Create Date: 2023-10-18 16:29:48.219822

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("city_unique_constraint", 'city', ['city_id'])
    op.create_unique_constraint("telegram_user_unique_constraint", 'telegram_user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("telegram_user_unique_constraint", 'telegram_user', type_='unique')
    op.drop_constraint("city_unique_constraint", 'city', type_='unique')
    # ### end Alembic commands ###
